/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import { NCN_PROGRAM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';
import {
  getMetaMerkleLeafDecoder,
  getMetaMerkleLeafEncoder,
  getStakeMerkleLeafDecoder,
  getStakeMerkleLeafEncoder,
  type MetaMerkleLeaf,
  type MetaMerkleLeafArgs,
  type StakeMerkleLeaf,
  type StakeMerkleLeafArgs,
} from '../types';

export const VERIFY_MERKLE_DISCRIMINATOR = 31;

export function getVerifyMerkleDiscriminatorBytes() {
  return getU8Encoder().encode(VERIFY_MERKLE_DISCRIMINATOR);
}

export type VerifyMerkleInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountConsensusResult extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConsensusResult extends string
        ? ReadonlyAccount<TAccountConsensusResult>
        : TAccountConsensusResult,
      ...TRemainingAccounts,
    ]
  >;

export type VerifyMerkleInstructionData = {
  discriminator: number;
  metaMerkleProof: Array<ReadonlyUint8Array>;
  metaMerkleLeaf: MetaMerkleLeaf;
  stakeMerkleProof: Option<Array<ReadonlyUint8Array>>;
  stakeMerkleLeaf: Option<StakeMerkleLeaf>;
};

export type VerifyMerkleInstructionDataArgs = {
  metaMerkleProof: Array<ReadonlyUint8Array>;
  metaMerkleLeaf: MetaMerkleLeafArgs;
  stakeMerkleProof: OptionOrNullable<Array<ReadonlyUint8Array>>;
  stakeMerkleLeaf: OptionOrNullable<StakeMerkleLeafArgs>;
};

export function getVerifyMerkleInstructionDataEncoder(): Encoder<VerifyMerkleInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      [
        'metaMerkleProof',
        getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32)),
      ],
      ['metaMerkleLeaf', getMetaMerkleLeafEncoder()],
      [
        'stakeMerkleProof',
        getOptionEncoder(
          getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32))
        ),
      ],
      ['stakeMerkleLeaf', getOptionEncoder(getStakeMerkleLeafEncoder())],
    ]),
    (value) => ({ ...value, discriminator: VERIFY_MERKLE_DISCRIMINATOR })
  );
}

export function getVerifyMerkleInstructionDataDecoder(): Decoder<VerifyMerkleInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['metaMerkleProof', getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ['metaMerkleLeaf', getMetaMerkleLeafDecoder()],
    [
      'stakeMerkleProof',
      getOptionDecoder(getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))),
    ],
    ['stakeMerkleLeaf', getOptionDecoder(getStakeMerkleLeafDecoder())],
  ]);
}

export function getVerifyMerkleInstructionDataCodec(): Codec<
  VerifyMerkleInstructionDataArgs,
  VerifyMerkleInstructionData
> {
  return combineCodec(
    getVerifyMerkleInstructionDataEncoder(),
    getVerifyMerkleInstructionDataDecoder()
  );
}

export type VerifyMerkleInput<TAccountConsensusResult extends string = string> =
  {
    consensusResult: Address<TAccountConsensusResult>;
    metaMerkleProof: VerifyMerkleInstructionDataArgs['metaMerkleProof'];
    metaMerkleLeaf: VerifyMerkleInstructionDataArgs['metaMerkleLeaf'];
    stakeMerkleProof: VerifyMerkleInstructionDataArgs['stakeMerkleProof'];
    stakeMerkleLeaf: VerifyMerkleInstructionDataArgs['stakeMerkleLeaf'];
  };

export function getVerifyMerkleInstruction<
  TAccountConsensusResult extends string,
  TProgramAddress extends Address = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
>(
  input: VerifyMerkleInput<TAccountConsensusResult>,
  config?: { programAddress?: TProgramAddress }
): VerifyMerkleInstruction<TProgramAddress, TAccountConsensusResult> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    consensusResult: {
      value: input.consensusResult ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [getAccountMeta(accounts.consensusResult)],
    programAddress,
    data: getVerifyMerkleInstructionDataEncoder().encode(
      args as VerifyMerkleInstructionDataArgs
    ),
  } as VerifyMerkleInstruction<TProgramAddress, TAccountConsensusResult>;

  return instruction;
}

export type ParsedVerifyMerkleInstruction<
  TProgram extends string = typeof NCN_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    consensusResult: TAccountMetas[0];
  };
  data: VerifyMerkleInstructionData;
};

export function parseVerifyMerkleInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedVerifyMerkleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      consensusResult: getNextAccount(),
    },
    data: getVerifyMerkleInstructionDataDecoder().decode(instruction.data),
  };
}
