/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  getMetaMerkleLeafBundleDecoder,
  getMetaMerkleLeafBundleEncoder,
  type MetaMerkleLeafBundle,
  type MetaMerkleLeafBundleArgs,
} from '.';

export type MetaMerkleSnapshot = {
  root: ReadonlyUint8Array;
  leafBundles: Array<MetaMerkleLeafBundle>;
  slot: bigint;
};

export type MetaMerkleSnapshotArgs = {
  root: ReadonlyUint8Array;
  leafBundles: Array<MetaMerkleLeafBundleArgs>;
  slot: number | bigint;
};

export function getMetaMerkleSnapshotEncoder(): Encoder<MetaMerkleSnapshotArgs> {
  return getStructEncoder([
    ['root', fixEncoderSize(getBytesEncoder(), 32)],
    ['leafBundles', getArrayEncoder(getMetaMerkleLeafBundleEncoder())],
    ['slot', getU64Encoder()],
  ]);
}

export function getMetaMerkleSnapshotDecoder(): Decoder<MetaMerkleSnapshot> {
  return getStructDecoder([
    ['root', fixDecoderSize(getBytesDecoder(), 32)],
    ['leafBundles', getArrayDecoder(getMetaMerkleLeafBundleDecoder())],
    ['slot', getU64Decoder()],
  ]);
}

export function getMetaMerkleSnapshotCodec(): Codec<
  MetaMerkleSnapshotArgs,
  MetaMerkleSnapshot
> {
  return combineCodec(
    getMetaMerkleSnapshotEncoder(),
    getMetaMerkleSnapshotDecoder()
  );
}
