/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  getMetaMerkleLeafDecoder,
  getMetaMerkleLeafEncoder,
  getStakeMerkleLeafDecoder,
  getStakeMerkleLeafEncoder,
  type MetaMerkleLeaf,
  type MetaMerkleLeafArgs,
  type StakeMerkleLeaf,
  type StakeMerkleLeafArgs,
} from '.';

export type MetaMerkleLeafBundle = {
  metaMerkleLeaf: MetaMerkleLeaf;
  stakeMerkleLeaves: Array<StakeMerkleLeaf>;
  proof: Option<Array<ReadonlyUint8Array>>;
};

export type MetaMerkleLeafBundleArgs = {
  metaMerkleLeaf: MetaMerkleLeafArgs;
  stakeMerkleLeaves: Array<StakeMerkleLeafArgs>;
  proof: OptionOrNullable<Array<ReadonlyUint8Array>>;
};

export function getMetaMerkleLeafBundleEncoder(): Encoder<MetaMerkleLeafBundleArgs> {
  return getStructEncoder([
    ['metaMerkleLeaf', getMetaMerkleLeafEncoder()],
    ['stakeMerkleLeaves', getArrayEncoder(getStakeMerkleLeafEncoder())],
    [
      'proof',
      getOptionEncoder(getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32))),
    ],
  ]);
}

export function getMetaMerkleLeafBundleDecoder(): Decoder<MetaMerkleLeafBundle> {
  return getStructDecoder([
    ['metaMerkleLeaf', getMetaMerkleLeafDecoder()],
    ['stakeMerkleLeaves', getArrayDecoder(getStakeMerkleLeafDecoder())],
    [
      'proof',
      getOptionDecoder(getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))),
    ],
  ]);
}

export function getMetaMerkleLeafBundleCodec(): Codec<
  MetaMerkleLeafBundleArgs,
  MetaMerkleLeafBundle
> {
  return combineCodec(
    getMetaMerkleLeafBundleEncoder(),
    getMetaMerkleLeafBundleDecoder()
  );
}
