/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type MetaMerkleLeaf = {
  votingWallet: Address;
  voteAccount: Address;
  stakeMerkleRoot: ReadonlyUint8Array;
  activeStake: bigint;
};

export type MetaMerkleLeafArgs = {
  votingWallet: Address;
  voteAccount: Address;
  stakeMerkleRoot: ReadonlyUint8Array;
  activeStake: number | bigint;
};

export function getMetaMerkleLeafEncoder(): Encoder<MetaMerkleLeafArgs> {
  return getStructEncoder([
    ['votingWallet', getAddressEncoder()],
    ['voteAccount', getAddressEncoder()],
    ['stakeMerkleRoot', fixEncoderSize(getBytesEncoder(), 32)],
    ['activeStake', getU64Encoder()],
  ]);
}

export function getMetaMerkleLeafDecoder(): Decoder<MetaMerkleLeaf> {
  return getStructDecoder([
    ['votingWallet', getAddressDecoder()],
    ['voteAccount', getAddressDecoder()],
    ['stakeMerkleRoot', fixDecoderSize(getBytesDecoder(), 32)],
    ['activeStake', getU64Decoder()],
  ]);
}

export function getMetaMerkleLeafCodec(): Codec<
  MetaMerkleLeafArgs,
  MetaMerkleLeaf
> {
  return combineCodec(getMetaMerkleLeafEncoder(), getMetaMerkleLeafDecoder());
}
