/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type StakeMerkleLeaf = {
  votingWallet: Address;
  stakeAccount: Address;
  activeStake: bigint;
};

export type StakeMerkleLeafArgs = {
  votingWallet: Address;
  stakeAccount: Address;
  activeStake: number | bigint;
};

export function getStakeMerkleLeafEncoder(): Encoder<StakeMerkleLeafArgs> {
  return getStructEncoder([
    ['votingWallet', getAddressEncoder()],
    ['stakeAccount', getAddressEncoder()],
    ['activeStake', getU64Encoder()],
  ]);
}

export function getStakeMerkleLeafDecoder(): Decoder<StakeMerkleLeaf> {
  return getStructDecoder([
    ['votingWallet', getAddressDecoder()],
    ['stakeAccount', getAddressDecoder()],
    ['activeStake', getU64Decoder()],
  ]);
}

export function getStakeMerkleLeafCodec(): Codec<
  StakeMerkleLeafArgs,
  StakeMerkleLeaf
> {
  return combineCodec(getStakeMerkleLeafEncoder(), getStakeMerkleLeafDecoder());
}
