use jito_bytemuck::AccountDeserialize;
use ncn_program_core::{
    consensus_result::ConsensusResult,
    error::NCNProgramError,
    merkle::{verify_helper, MetaMerkleLeaf, StakeMerkleLeaf},
};
use solana_program::{
    account_info::AccountInfo, entrypoint::ProgramResult, msg, program_error::ProgramError,
    pubkey::Pubkey,
};

/// Verifies that the Merkle root in `ConsensusResult` is valid given the provided leaves and proofs.
///
/// If both `StakeMerkleLeaf` and `MetaMerkleLeaf` are provided, the function first verifies that
/// the stake leaf is included in the StakeMerkleTree (via `stake_merkle_proof`), then verifies that
/// the MetaMerkleLeaf is included in the MetaMerkleTree (via `meta_merkle_proof`).
///
/// If only the MetaMerkleLeaf and its proof are provided, only the top-level MetaMerkleTree verification is performed.
///
/// ### Parameters:
/// - `meta_merkle_proof`: Proof of inclusion for the MetaMerkleLeaf in the MetaMerkleTree
/// - `meta_merkle_leaf`: Merkle leaf representing a vote account and its delegated stake (via a StakeMerkleTree)
/// - `stake_merkle_proof`: [Optional] Proof of inclusion for the StakeMerkleLeaf in the StakeMerkleTree
/// - `stake_merkle_leaf`: [Optional] Merkle leaf representing a stake account
///
/// ### Accounts:
/// 1. `[]` consensus_result: The account containing the expected top-level Merkle root
pub fn process_verify_merkle(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    meta_merkle_proof: Vec<[u8; 32]>,
    meta_merkle_leaf: MetaMerkleLeaf,
    stake_merkle_proof: Option<Vec<[u8; 32]>>,
    stake_merkle_leaf: Option<StakeMerkleLeaf>,
) -> ProgramResult {
    let [consensus_result] = accounts else {
        msg!("Error: Not enough account keys provided");
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    let result_data = consensus_result.try_borrow_data()?;
    let result_account = ConsensusResult::try_from_slice_unchecked(&result_data)?;

    // Enforce safaty checks for mutability, ownership and discriminator.
    ConsensusResult::load(
        program_id,
        consensus_result,
        result_account.ncn(),
        result_account.epoch(),
        false,
    )?;

    if stake_merkle_leaf.is_some() && stake_merkle_proof.is_some() {
        let proof_vec = stake_merkle_proof.unwrap();
        let stake_merkle_leaf_data = stake_merkle_leaf.unwrap();
        let leaf_content = &stake_merkle_leaf_data.hash().to_bytes();

        // Check that the root generated by the proof and StakeMerkleLeaf matches
        // root in MetaMerkleLeaf.
        verify_helper(
            leaf_content,
            proof_vec,
            meta_merkle_leaf.stake_merkle_root.0,
        )?;
    } else if stake_merkle_leaf.is_some() || stake_merkle_proof.is_some() {
        return Err(NCNProgramError::InvalidVerifyMerkleInputs.into());
    }

    let leaf_content = &meta_merkle_leaf.hash().to_bytes();

    // Check that the root generated by the proof and MetaMerkleLeaf matches
    // root in ConsensusResult.
    verify_helper(
        leaf_content,
        meta_merkle_proof,
        result_account.merkle_root().into(),
    )?;

    Ok(())
}
